name: CI Pipeline for Zonk

on:
  pull_request:
    branches: [develop]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Перевірка наявності схваленого код-рев’ю
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const reviews = await github.rest.pulls.listReviews({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
            });

            const approved = reviews.data.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено");
            } else {
              console.log("Код-рев’ю схвалено");
            }

  analysis:
    runs-on: ubuntu-latest
    needs: review-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=zonk_project
            -Dsonar.organization=d4bleguninvador
            -Dsonar.host.url=https://sonarcloud.io
