name: CI Pipeline for Zonk

on:
  pull_request:
    branches: [develop]

jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Перевірка наявності схваленого код-рев’ю
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const reviews = await github.rest.pulls.listReviews({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
            });

            const approved = reviews.data.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено");
            } else {
              console.log("Код-рев’ю схвалено");

  analysis:
    runs-on: ubuntu-latest
    needs: review-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flake8 for linting
        run: flake8 src/ --statistics --count

      - name: Run Pytest with coverage
        run: pytest --cov=src --cov-report=xml --cov-report=term

      - name: Run Cloc for code metrics
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=D4bleGunInVador_zonk_project
            -Dsonar.organization=d4bleguninvador
            -Dsonar.host.url=https://sonarcloud.io
