#
name: CI Pipeline for Zonk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Перевірка наявності схваленого код-рев’ю
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr || !pr.number) {
              core.setFailed("Цей workflow має запускатися лише з pull request.");
              return;
            }

            const prNumber = pr.number;
            const { owner, repo } = context.repo;

            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: prNumber,
            });

            const approved = reviews.data.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено");
            } else {
              console.log("Код-рев’ю схвалено");
            }


  analysis:
    runs-on: ubuntu-latest
    needs: review-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 cloc

      - name: Setup virtual display (Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run Flake8 for linting
        run: flake8 src/ --statistics --count

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run Pytest with coverage
        env:
          DISPLAY: :99
        run: pytest --cov=src --cov-report=xml --cov-report=term src/tests

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Run Cloc for code metrics
        run: |
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=D4bleGunInVador_zonk_project
            -Dsonar.organization=d4bleguninvador
            -Dsonar.host.url=https://sonarcloud.io
